import {StyleSheet} from 'react-native';
import {COLORS} from '../constants/theme';

export const appStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.bg,
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 90,
  },
  rowBetween: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  appTitle: {
    fontSize: 28,
    fontWeight: '800',
    color: COLORS.text,
  },
  softText: {
    color: COLORS.textSoft,
    fontSize: 14,
    marginTop: 4,
  },
  summaryCard: {
    backgroundColor: COLORS.primary,
    borderRadius: 16,
    padding: 14,
    marginBottom: 16,
  },
  summaryLabel: {
    color: '#DCE5FF',
    fontSize: 12,
    fontWeight: '700',
  },
  summaryText: {
    marginTop: 8,
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '700',
  },
  summaryPercent: {
    marginTop: 6,
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
    textAlign: 'right',
  },
  progressBar: {
    marginTop: 10,
    height: 8,
    borderRadius: 8,
    backgroundColor: '#5A76D9',
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: '#66D990',
  },
  sectionTitle: {
    color: COLORS.text,
    fontSize: 22,
    fontWeight: '700',
    marginBottom: 12,
  },
  emptyCard: {
    backgroundColor: COLORS.card,
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: COLORS.line,
    marginBottom: 12,
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.text,
    marginBottom: 6,
  },
  medicineCard: {
    backgroundColor: COLORS.card,
    borderRadius: 14,
    borderLeftWidth: 4,
    borderLeftColor: COLORS.orange,
    padding: 14,
    marginBottom: 12,
  },
  medicineName: {
    color: COLORS.text,
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 4,
  },
  actionRow: {
    marginTop: 12,
    flexDirection: 'row',
    gap: 8,
  },
  actionButton: {
    flex: 1,
    paddingVertical: 11,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionButtonText: {
    color: '#FFF',
    fontWeight: '700',
    fontSize: 14,
  },
  actionPrimary: {
    backgroundColor: COLORS.primary,
  },
  actionDanger: {
    backgroundColor: COLORS.red,
  },
  bigButton: {
    marginTop: 8,
    backgroundColor: COLORS.primary,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bigButtonText: {
    color: '#FFF',
    fontWeight: '800',
    fontSize: 15,
  },
  countBadge: {
    backgroundColor: '#E3EBFF',
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  countBadgeText: {
    color: COLORS.primaryDark,
    fontSize: 13,
    fontWeight: '700',
  },
  historyDateNav: {
    marginTop: 16,
    marginBottom: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: COLORS.card,
    borderRadius: 12,
    padding: 10,
    borderWidth: 1,
    borderColor: COLORS.line,
  },
  navRoundButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#EEF2FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  navRoundButtonText: {
    color: COLORS.primaryDark,
    fontWeight: '700',
    fontSize: 18,
  },
  historyDateText: {
    color: COLORS.text,
    fontWeight: '700',
    fontSize: 15,
    textTransform: 'capitalize',
  },
  historyCard: {
    backgroundColor: COLORS.card,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.line,
    padding: 12,
    marginBottom: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  statusPill: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
  },
  statusPillText: {
    color: '#FFF',
    fontWeight: '700',
    fontSize: 12,
  },
  tipCard: {
    marginTop: 10,
    backgroundColor: COLORS.card,
    borderRadius: 14,
    borderLeftWidth: 4,
    borderLeftColor: COLORS.primary,
    borderWidth: 1,
    borderColor: COLORS.line,
    padding: 14,
  },
  tabBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: 'row',
    backgroundColor: '#FFF',
    borderTopWidth: 1,
    borderTopColor: COLORS.line,
  },
  tabButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
    borderTopWidth: 3,
    borderTopColor: 'transparent',
  },
  tabButtonActive: {
    borderTopColor: COLORS.primary,
  },
  tabIcon: {
    fontSize: 18,
  },
  tabLabel: {
    marginTop: 2,
    fontSize: 11,
    color: COLORS.textSoft,
    fontWeight: '600',
  },
  tabLabelActive: {
    color: COLORS.primary,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'flex-end',
  },
  modalCard: {
    backgroundColor: '#FFF',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    padding: 16,
  },
  modalTitle: {
    color: COLORS.text,
    fontWeight: '800',
    fontSize: 20,
    marginBottom: 12,
  },
  inputLabel: {
    color: COLORS.text,
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 6,
  },
  input: {
    borderWidth: 1,
    borderColor: COLORS.line,
    borderRadius: 10,
    backgroundColor: '#FFF',
    marginBottom: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: COLORS.text,
  },
  notesInput: {
    minHeight: 74,
    textAlignVertical: 'top',
  },
  frequencyWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 10,
  },
  frequencyItem: {
    borderWidth: 1,
    borderColor: COLORS.line,
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  frequencyItemActive: {
    borderColor: COLORS.primary,
    backgroundColor: '#EAF0FF',
  },
  frequencyItemText: {
    color: COLORS.textSoft,
    fontSize: 13,
    fontWeight: '600',
  },
  frequencyItemTextActive: {
    color: COLORS.primaryDark,
  },
  cancelButton: {
    backgroundColor: '#EEF1F6',
  },
  cancelButtonText: {
    color: COLORS.text,
    fontWeight: '700',
    fontSize: 14,
  },
});
