import { StyleSheet } from 'react-native';
import { ThemePalette } from '../constants/themePalettes';

export function createAppStyles(
  c: ThemePalette,
  fontScale: number,
  largeTouch: boolean,
  highVisibilityBorders: boolean,
) {
  const fs = (n: number) => Math.round(n * fontScale);
  const tx = largeTouch ? 5 : 0;
  const cardBorder = highVisibilityBorders ? 2 : 1;
  const font = 'Outfit-Bold';
  const shadow = {
    shadowColor: '#162033',
    shadowOffset: { width: 0, height: 7 },
    shadowOpacity: 0.07,
    shadowRadius: 14,
    elevation: 3,
  };

  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: c.bg,
    },
    scrollContent: {
      paddingHorizontal: 14 + (largeTouch ? 2 : 0),
      paddingTop: 12 + tx,
      paddingBottom: 96 + tx,
    },
    rowBetween: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    medicineHeaderRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 8,
    },
    medicineHeaderInfo: {
      flex: 1,
      minWidth: 0,
    },
    medicineTimePill: {
      flexShrink: 0,
      borderRadius: 999,
      paddingHorizontal: 9,
      paddingVertical: 5,
      backgroundColor: '#FFF3D8',
      borderWidth: 0,
    },
    medicineTimeText: {
      fontFamily: font,
      color: c.text,
      fontSize: fs(14),
      fontWeight: 'normal',
    },
    appTitle: {
      fontFamily: font,
      fontSize: fs(27),
      fontWeight: 'normal',
      color: c.primary,
    },
    greetingTitle: {
      fontFamily: font,
      fontSize: fs(24),
      fontWeight: 'normal',
      color: c.text,
      lineHeight: fs(25),
    },
    headerRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 4,
    },
    settingsHeaderButton: {
      width: 48 + (largeTouch ? 6 : 0),
      height: 48 + (largeTouch ? 6 : 0),
      borderRadius: 24 + (largeTouch ? 3 : 0),
      backgroundColor: c.navButtonBg,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: highVisibilityBorders ? 2 : 0,
      borderColor: c.text,
    },
    settingsHeaderIcon: {
      fontFamily: font,
      color: c.primaryDark,
      fontSize: fs(18),
      fontWeight: 'normal',
    },
    avatarButton: {
      width: 52,
      height: 52,
      borderRadius: 26,
      backgroundColor: c.navButtonBg,
      alignItems: 'center',
      justifyContent: 'center',
      position: 'relative',
      ...shadow,
    },
    avatarText: {
      fontFamily: font,
      color: c.primary,
      fontSize: fs(22),
      fontWeight: 'normal',
    },
    onlineDot: {
      position: 'absolute',
      right: 2,
      bottom: 2,
      width: 14,
      height: 14,
      borderRadius: 7,
      backgroundColor: c.green,
      borderWidth: 2,
      borderColor: '#FFFFFF',
    },
    softText: {
      fontFamily: font,
      color: c.textSoft,
      fontSize: fs(12),
      marginTop: 4,
    },
    summaryCard: {
      backgroundColor: c.primaryDark,
      borderRadius: 16,
      padding: 14 + tx,
      marginBottom: 16,
      borderWidth: highVisibilityBorders ? 2 : 0,
      borderColor: c.line,
    },
    summaryLabel: {
      fontFamily: font,
      color: c.summaryMuted,
      fontSize: fs(13),
      fontWeight: 'normal',
    },
    summaryText: {
      fontFamily: font,
      marginTop: 8,
      color: '#FFFFFF',
      fontSize: fs(20),
      fontWeight: 'normal',
    },
    summaryPercent: {
      fontFamily: font,
      marginTop: 6,
      color: '#FFFFFF',
      fontSize: fs(14),
      fontWeight: 'normal',
      textAlign: 'right',
    },
    metricsRow: {
      flexDirection: 'row',
      gap: 8,
      marginBottom: 14,
    },
    metricCard: {
      flex: 1,
      borderRadius: 12,
      paddingVertical: 13 + tx,
      paddingHorizontal: 10,
      borderWidth: 0,
      minHeight: 96,
    },
    metricCardTaken: {
      backgroundColor: c.metricTakenBg,
      borderColor: c.metricTakenBorder,
    },
    metricCardMissed: {
      backgroundColor: c.metricMissedBg,
      borderColor: c.metricMissedBorder,
    },
    metricCardPending: {
      backgroundColor: c.metricPendingBg,
      borderColor: c.metricPendingBorder,
    },
    metricTitle: {
      fontFamily: font,
      color: '#FFFFFF',
      fontSize: fs(11),
      fontWeight: 'normal',
    },
    metricValue: {
      fontFamily: font,
      marginTop: 4,
      color: '#FFFFFF',
      fontSize: fs(28),
      fontWeight: 'normal',
    },
    progressBar: {
      marginTop: 10,
      height: 10 + (largeTouch ? 2 : 0),
      borderRadius: 8,
      backgroundColor: c.progressTrack,
      overflow: 'hidden',
    },
    progressFill: {
      height: '100%',
      backgroundColor: c.yellow,
    },
    sectionTitle: {
      fontFamily: font,
      color: c.text,
      fontSize: fs(18),
      fontWeight: 'normal',
      marginBottom: 12,
    },
    emptyCard: {
      backgroundColor: c.card,
      borderRadius: 16,
      padding: 16 + tx,
      borderWidth: cardBorder,
      borderColor: c.line,
      marginBottom: 12,
      ...shadow,
    },
    emptyTitle: {
      fontFamily: font,
      fontSize: fs(16),
      fontWeight: 'normal',
      color: c.text,
      marginBottom: 6,
    },
    medicineCard: {
      backgroundColor: c.card,
      borderRadius: 16,
      borderLeftWidth: 5,
      borderLeftColor: c.orange,
      padding: 14 + tx,
      marginBottom: 12,
      borderWidth: 0,
      borderColor: c.line,
      ...shadow,
    },
    medicineName: {
      fontFamily: font,
      color: c.text,
      fontSize: fs(15),
      fontWeight: 'normal',
      marginBottom: 4,
    },
    actionRow: {
      marginTop: 12,
      flexDirection: 'row',
      gap: 8,
    },
    loggedTodayTag: {
      marginTop: 10,
      borderRadius: 10,
      paddingVertical: 7 + tx,
      paddingHorizontal: 10,
      backgroundColor: c.loggedTagBg,
    },
    loggedTodayTagText: {
      fontFamily: font,
      color: c.primaryDark,
      fontSize: fs(13),
      fontWeight: 'normal',
    },
    actionButton: {
      flex: 1,
      paddingVertical: 11 + tx,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: largeTouch ? 52 : 44,
    },
    actionButtonText: {
      fontFamily: font,
      color: '#FFF',
      fontWeight: 'normal',
      fontSize: fs(15),
    },
    iconTextRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
    },
    inlineIconText: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    actionPrimary: {
      backgroundColor: c.primary,
    },
    actionDanger: {
      backgroundColor: c.red,
    },
    actionNeutral: {
      backgroundColor: c.cancelButtonBg,
    },
    actionViewSoft: {
      backgroundColor: c.navButtonBg,
    },
    actionEditSoft: {
      backgroundColor: '#FFF4DD',
    },
    actionDeleteSoft: {
      backgroundColor: '#FFE9E9',
    },
    neutralButtonText: {
      fontFamily: font,
      color: c.primaryDark,
      fontWeight: 'normal',
      fontSize: fs(15),
    },
    viewSoftText: {
      fontFamily: font,
      color: c.primaryDark,
      fontWeight: 'normal',
      fontSize: fs(13),
    },
    editSoftText: {
      fontFamily: font,
      color: c.yellow,
      fontWeight: 'normal',
      fontSize: fs(13),
    },
    deleteSoftText: {
      fontFamily: font,
      color: c.red,
      fontWeight: 'normal',
      fontSize: fs(13),
    },
    bigButton: {
      marginTop: 8,
      backgroundColor: c.orange,
      borderRadius: 12,
      paddingVertical: 14 + tx,
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: largeTouch ? 56 : 48,
    },
    bigButtonText: {
      fontFamily: font,
      color: '#FFF',
      fontWeight: 'normal',
      fontSize: fs(15),
    },
    countBadge: {
      backgroundColor: '#FFF1DD',
      borderRadius: 999,
      paddingHorizontal: 12,
      paddingVertical: 8 + tx,
    },
    countBadgeText: {
      fontFamily: font,
      color: c.orange,
      fontSize: fs(11),
      fontWeight: 'normal',
    },
    historyDateNav: {
      marginTop: 16,
      marginBottom: 14,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: c.card,
      borderRadius: 12,
      padding: 10 + tx,
      borderWidth: cardBorder,
      borderColor: c.line,
    },
    navRoundButton: {
      width: 36 + (largeTouch ? 10 : 0),
      height: 36 + (largeTouch ? 10 : 0),
      borderRadius: 18 + (largeTouch ? 5 : 0),
      backgroundColor: c.navButtonBg,
      alignItems: 'center',
      justifyContent: 'center',
    },
    navRoundButtonText: {
      fontFamily: font,
      color: c.primaryDark,
      fontWeight: 'normal',
      fontSize: fs(18),
    },
    historyDateText: {
      fontFamily: font,
      color: c.text,
      fontWeight: 'normal',
      fontSize: fs(15),
      textTransform: 'capitalize',
    },
    historyCard: {
      backgroundColor: c.card,
      borderRadius: 14,
      borderWidth: 0,
      borderColor: c.line,
      padding: 12 + tx,
      marginBottom: 10,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      ...shadow,
    },
    statusPill: {
      paddingHorizontal: 12,
      paddingVertical: 6 + tx,
      borderRadius: 20,
    },
    statusPillText: {
      fontFamily: font,
      color: '#FFF',
      fontWeight: 'normal',
      fontSize: fs(12),
    },
    tipCard: {
      marginTop: 10,
      backgroundColor: c.card,
      borderRadius: 14,
      borderLeftWidth: 4,
      borderLeftColor: c.primary,
      borderWidth: cardBorder,
      borderColor: c.line,
      padding: 14 + tx,
    },
    tabBar: {
      position: 'absolute',
      left: 8,
      right: 8,
      bottom: 6,
      flexDirection: 'row',
      backgroundColor: c.tabBarBg,
      borderRadius: 18,
      borderTopWidth: 0,
      paddingHorizontal: 4,
      paddingVertical: 4,
      ...shadow,
    },
    tabButton: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 6 + tx,
      borderTopWidth: 0,
      minHeight: largeTouch ? 58 : 50,
    },
    tabButtonActive: {
      borderTopColor: 'transparent',
    },
    tabButtonAdd: {
      marginTop: -20,
    },
    tabIcon: {
      width: 24,
      height: 24,
      alignItems: 'center',
      justifyContent: 'center',
    },
    tabIconActive: {
      color: c.primary,
    },
    tabIconAdd: {
      width: 52,
      height: 52,
      borderRadius: 26,
      backgroundColor: c.primary,
      overflow: 'hidden',
      alignItems: 'center',
      justifyContent: 'center',
      ...shadow,
    },
    tabLabel: {
      fontFamily: font,
      marginTop: 2,
      fontSize: fs(10),
      color: c.textSoft,
      fontWeight: 'normal',
    },
    tabLabelActive: {
      color: c.primary,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.45)',
      justifyContent: 'flex-end',
    },
    modalCard: {
      backgroundColor: c.modalCardBg,
      borderTopLeftRadius: 16,
      borderTopRightRadius: 16,
      padding: 16 + tx,
      maxHeight: '90%',
    },
    modalScroll: {
      flexGrow: 0,
    },
    modalTitle: {
      fontFamily: font,
      color: c.text,
      fontWeight: 'normal',
      fontSize: fs(20),
      marginBottom: 12,
    },
    inputLabel: {
      fontFamily: font,
      color: c.text,
      fontSize: fs(16),
      fontWeight: 'normal',
      marginBottom: 6,
    },
    input: {
      fontFamily: font,
      borderWidth: cardBorder,
      borderColor: c.line,
      borderRadius: 10,
      backgroundColor: c.inputBg,
      marginBottom: 6,
      paddingHorizontal: 12,
      paddingVertical: 10 + tx,
      color: c.text,
      fontSize: fs(16),
    },
    charCounter: {
      fontFamily: font,
      color: c.textSoft,
      fontSize: fs(11),
      fontWeight: 'normal',
      textAlign: 'right',
      marginTop: -2,
      marginBottom: 8,
    },
    notesInput: {
      minHeight: 74,
      textAlignVertical: 'top',
    },
    frequencyWrap: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      marginBottom: 10,
    },
    frequencyItem: {
      borderWidth: cardBorder,
      borderColor: c.line,
      borderRadius: 20,
      paddingHorizontal: 12,
      paddingVertical: 8 + tx,
    },
    frequencyItemActive: {
      borderColor: c.primary,
      backgroundColor: c.frequencyActiveBg,
    },
    frequencyItemText: {
      fontFamily: font,
      color: c.textSoft,
      fontSize: fs(13),
      fontWeight: 'normal',
    },
    frequencyItemTextActive: {
      color: c.primaryDark,
    },
    cancelButton: {
      backgroundColor: c.cancelButtonBg,
    },
    cancelButtonText: {
      fontFamily: font,
      color: c.text,
      fontWeight: 'normal',
      fontSize: fs(14),
    },
    settingsSectionTitle: {
      fontFamily: font,
      color: c.primaryDark,
      fontSize: fs(13),
      fontWeight: 'normal',
      marginTop: 18,
      marginBottom: 8,
      letterSpacing: 0.5,
    },
    settingsRow: {
      backgroundColor: c.card,
      borderRadius: 12,
      padding: 14 + tx,
      marginBottom: 8,
      borderWidth: cardBorder,
      borderColor: c.line,
    },
    settingsRowLabel: {
      fontFamily: font,
      color: c.text,
      fontSize: fs(16),
      fontWeight: 'normal',
    },
    settingsRowHint: {
      fontFamily: font,
      color: c.textSoft,
      fontSize: fs(13),
      marginTop: 4,
    },
    settingsChipRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      marginTop: 10,
    },
    settingsChip: {
      borderWidth: cardBorder,
      borderColor: c.line,
      borderRadius: 20,
      paddingHorizontal: 14,
      paddingVertical: 10 + tx,
      backgroundColor: c.inputBg,
    },
    settingsChipActive: {
      borderColor: c.primary,
      backgroundColor: c.frequencyActiveBg,
    },
    settingsChipText: {
      fontFamily: font,
      color: c.textSoft,
      fontSize: fs(14),
      fontWeight: 'normal',
    },
    settingsChipTextActive: {
      color: c.primaryDark,
      fontWeight: 'normal',
    },
    settingsOptionGrid: {
      flexDirection: 'row',
      gap: 8,
      marginTop: 10,
    },
    visualOptionCard: {
      flex: 1,
      minWidth: 0,
      borderWidth: cardBorder,
      borderColor: c.line,
      borderRadius: 12,
      backgroundColor: c.inputBg,
      padding: 10 + tx,
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'hidden',
    },
    visualOptionCardActive: {
      borderColor: c.primary,
      backgroundColor: c.frequencyActiveBg,
    },
    visualOptionTitle: {
      fontFamily: font,
      color: c.text,
      fontSize: fs(12),
      fontWeight: 'normal',
      marginTop: 4,
      textAlign: 'center',
    },
    visualOptionHint: {
      fontFamily: font,
      color: c.textSoft,
      fontSize: fs(10),
      fontWeight: 'normal',
      marginTop: 2,
      textAlign: 'center',
    },
    fontPreviewSmall: {
      fontFamily: font,
      color: c.textSoft,
      fontSize: fs(14),
      fontWeight: 'normal',
    },
    fontPreviewMedium: {
      fontFamily: font,
      color: c.text,
      fontSize: fs(18),
      fontWeight: 'normal',
    },
    fontPreviewLarge: {
      fontFamily: font,
      color: c.primary,
      fontSize: fs(20),
      fontWeight: 'normal',
    },
    themePreview: {
      width: '100%',
      height: 36,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: c.line,
      overflow: 'hidden',
      flexDirection: 'row',
    },
    themePreviewBand: {
      flex: 1,
    },
    soundPreviewIcon: {
      fontFamily: font,
      color: c.primary,
      fontSize: fs(18),
      fontWeight: 'normal',
    },
    soundPreviewButton: {
      marginTop: 6,
      borderRadius: 8,
      paddingHorizontal: 8,
      paddingVertical: 4,
      backgroundColor: c.primary,
      alignSelf: 'center',
    },
    soundPreviewButtonText: {
      fontFamily: font,
      color: '#FFFFFF',
      fontSize: fs(9),
      fontWeight: 'normal',
    },
    settingsToggleRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginTop: 10,
    },
    settingsCloseBar: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 8,
    },
    settingsCloseText: {
      fontFamily: font,
      color: c.primary,
      fontSize: fs(16),
      fontWeight: 'normal',
    },
    settingsTitleMain: {
      fontFamily: font,
      color: c.text,
      fontSize: fs(22),
      fontWeight: 'normal',
    },
    sectionEyebrow: {
      fontFamily: font,
      color: c.primary,
      fontSize: fs(12),
      fontWeight: 'normal',
      textTransform: 'uppercase',
    },
    nextDoseCard: {
      backgroundColor: c.card,
      borderRadius: 22,
      padding: 16 + tx,
      marginTop: 16,
      marginBottom: 16,
      borderWidth: 0,
      borderColor: c.line,
      ...shadow,
    },
    medicineIconBox: {
      width: 52,
      height: 52,
      borderRadius: 14,
      backgroundColor: '#EEF5FF',
      alignItems: 'center',
      justifyContent: 'center',
    },
    medicineIconText: {
      fontFamily: font,
      color: c.primary,
      fontSize: fs(20),
      fontWeight: 'normal',
    },
    medicineIconBoxSmall: {
      width: 42,
      height: 42,
      borderRadius: 14,
      backgroundColor: '#EEF5FF',
      alignItems: 'center',
      justifyContent: 'center',
    },
    medicineIconSmallText: {
      fontFamily: font,
      color: c.primary,
      fontSize: fs(15),
      fontWeight: 'normal',
    },
    heroMedicineName: {
      fontFamily: font,
      color: c.text,
      fontSize: fs(22),
      fontWeight: 'normal',
      marginTop: 6,
    },
    doseInfoRow: {
      flexDirection: 'row',
      gap: 10,
      marginTop: 14,
      marginBottom: 12,
    },
    doseInfoBox: {
      flex: 1,
      borderRadius: 12,
      backgroundColor: c.inputBg,
      padding: 12 + tx,
      borderWidth: 0,
      alignItems: 'center',
      gap: 5,
    },
    doseTime: {
      fontFamily: font,
      color: c.text,
      fontSize: fs(19),
      fontWeight: 'normal',
    },
    doseMeta: {
      fontFamily: font,
      color: c.textSoft,
      fontSize: fs(13),
      fontWeight: 'normal',
      textAlign: 'center',
    },
    takeButton: {
      backgroundColor: c.teal,
      borderRadius: 12,
      paddingVertical: 13 + tx,
      alignItems: 'center',
      justifyContent: 'center',
    },
    postponeButton: {
      marginTop: 10,
      backgroundColor: c.metricMissedBg,
      borderRadius: 12,
      paddingVertical: 12 + tx,
      alignItems: 'center',
      borderWidth: cardBorder,
      borderColor: c.metricMissedBorder,
    },
    postponeButtonText: {
      fontFamily: font,
      color: c.red,
      fontWeight: 'normal',
      fontSize: fs(14),
    },
    warningTitle: {
      fontFamily: font,
      color: c.text,
      fontSize: fs(18),
      fontWeight: 'normal',
      marginBottom: 10,
    },
    missedCard: {
      backgroundColor: c.metricMissedBg,
      borderRadius: 20,
      borderWidth: 2,
      borderColor: c.red,
      padding: 14 + tx,
      marginBottom: 14,
    },
    missedTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      flex: 1,
    },
    missedIconCircle: {
      width: 42,
      height: 42,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#FFE0E0',
    },
    missedBadge: {
      backgroundColor: c.red,
      borderRadius: 14,
      paddingHorizontal: 10,
      paddingVertical: 5,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    missedBadgeText: {
      fontFamily: font,
      color: '#FFFFFF',
      fontSize: fs(11),
      fontWeight: 'normal',
    },
    miniSummaryRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 14,
    },
    simpleMedicineRow: {
      backgroundColor: c.card,
      borderRadius: 18,
      borderWidth: 0,
      borderColor: c.line,
      padding: 14 + tx,
      marginBottom: 10,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
      ...shadow,
    },
    homeTimeColumn: {
      alignItems: 'flex-end',
      gap: 5,
    },
    pendingBadge: {
      backgroundColor: '#FFF3D8',
      borderRadius: 999,
      paddingHorizontal: 8,
      paddingVertical: 4,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    pendingBadgeText: {
      fontFamily: font,
      color: c.yellow,
      fontSize: fs(10),
      fontWeight: 'normal',
    },
    activeBadge: {
      backgroundColor: '#E8FAF1',
      borderRadius: 14,
      paddingHorizontal: 10,
      paddingVertical: 5,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    activeBadgeText: {
      fontFamily: font,
      color: c.green,
      fontSize: fs(11),
      fontWeight: 'normal',
    },
    medicineDetailStrip: {
      backgroundColor: c.loggedTagBg,
      borderRadius: 10,
      padding: 10 + tx,
      marginVertical: 10,
    },
    optionGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      marginBottom: 12,
    },
    optionChip: {
      flexBasis: '30%',
      flexGrow: 1,
      borderWidth: cardBorder,
      borderColor: c.line,
      borderRadius: 12,
      backgroundColor: c.inputBg,
      paddingVertical: 11 + tx,
      paddingHorizontal: 8,
      alignItems: 'center',
    },
    optionChipActive: {
      borderColor: c.primary,
      backgroundColor: c.frequencyActiveBg,
    },
    optionChipText: {
      fontFamily: font,
      color: c.textSoft,
      fontSize: fs(12),
      fontWeight: 'normal',
      textAlign: 'center',
    },
    optionChipTextActive: {
      color: c.primaryDark,
    },
    formPanel: {
      backgroundColor: 'transparent',
      borderRadius: 0,
      padding: 0,
      borderWidth: 0,
    },
    calendarCard: {
      backgroundColor: c.card,
      borderRadius: 16,
      padding: 14 + tx,
      marginBottom: 16,
      borderWidth: 0,
      borderColor: c.line,
      ...shadow,
    },
    calendarGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      marginTop: 12,
    },
    calendarDay: {
      width: '14.28%',
      aspectRatio: 1,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 18,
    },
    calendarDayActive: {
      backgroundColor: c.primary,
    },
    calendarDayDose: {
      borderWidth: 1,
      borderColor: c.orange,
    },
    calendarLegendRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: 10,
    },
    calendarLegendDose: {
      fontFamily: font,
      color: c.orange,
      fontSize: fs(11),
      fontWeight: 'normal',
    },
    calendarLegendToday: {
      fontFamily: font,
      color: c.primary,
      fontSize: fs(11),
      fontWeight: 'normal',
    },
    calendarDayText: {
      fontFamily: font,
      color: c.text,
      fontSize: fs(12),
      fontWeight: 'normal',
    },
    calendarDayTextActive: {
      color: '#FFFFFF',
    },
    scheduleRow: {
      flexDirection: 'row',
      gap: 10,
      alignItems: 'center',
      marginBottom: 12,
    },
    scheduleTimePill: {
      width: 64,
      borderRadius: 14,
      paddingVertical: 12 + tx,
      backgroundColor: c.primary,
      alignItems: 'center',
    },
    scheduleTimeText: {
      fontFamily: font,
      color: '#FFFFFF',
      fontSize: fs(12),
      fontWeight: 'normal',
    },
    scheduleInfo: {
      flex: 1,
      backgroundColor: c.card,
      borderRadius: 14,
      borderWidth: 0,
      borderColor: c.line,
      padding: 12 + tx,
      ...shadow,
    },
    weeklyCard: {
      backgroundColor: c.card,
      borderRadius: 16,
      padding: 14 + tx,
      marginBottom: 16,
      ...shadow,
    },
    weeklyBars: {
      flexDirection: 'row',
      alignItems: 'flex-end',
      gap: 8,
      height: 120,
      marginTop: 10,
    },
    weeklyBarItem: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'flex-end',
    },
    weeklyBarTrack: {
      width: '100%',
      height: 86,
      borderRadius: 8,
      backgroundColor: c.progressTrack,
      overflow: 'hidden',
      justifyContent: 'flex-end',
    },
    weeklyBarFill: {
      width: '100%',
      borderRadius: 8,
    },
    weeklyDayText: {
      fontFamily: font,
      color: c.textSoft,
      fontSize: fs(11),
      fontWeight: 'normal',
      marginTop: 6,
    },
    streakCard: {
      backgroundColor: c.orange,
      borderRadius: 16,
      padding: 16 + tx,
      marginBottom: 18,
      ...shadow,
    },
    streakValue: {
      fontFamily: font,
      color: '#FFFFFF',
      fontSize: fs(28),
      fontWeight: 'normal',
    },
    streakText: {
      fontFamily: font,
      color: '#FFF0E8',
      fontSize: fs(13),
      fontWeight: 'normal',
      marginTop: 4,
    },
    searchBox: {
      backgroundColor: c.card,
      borderRadius: 14,
      paddingHorizontal: 14,
      paddingVertical: 12 + tx,
      marginTop: 16,
      marginBottom: 10,
      borderWidth: cardBorder,
      borderColor: c.line,
    },
    searchText: {
      fontFamily: font,
      color: c.textSoft,
      fontSize: fs(13),
      fontWeight: 'normal',
    },
    fieldCard: {
      backgroundColor: c.card,
      borderRadius: 16,
      padding: 14 + tx,
      marginBottom: 12,
      borderWidth: 0,
      ...shadow,
    },
    formLabelRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      marginBottom: 10,
    },
    formIconCircle: {
      width: 36,
      height: 36,
      borderRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
    },
    timePickerCard: {
      borderWidth: cardBorder,
      borderColor: c.line,
      borderRadius: 14,
      backgroundColor: c.inputBg,
      paddingHorizontal: 12,
      paddingVertical: 12 + tx,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 10,
    },
    timeStepper: {
      alignItems: 'center',
      gap: 7,
      minWidth: 76,
    },
    timeStepButton: {
      width: 34 + (largeTouch ? 8 : 0),
      height: 30 + (largeTouch ? 8 : 0),
      borderRadius: 10,
      backgroundColor: c.navButtonBg,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: highVisibilityBorders ? 2 : 0,
      borderColor: c.primary,
    },
    timeStepperValue: {
      fontFamily: font,
      color: c.text,
      fontSize: fs(28),
      fontWeight: 'normal',
      minWidth: 48,
      textAlign: 'center',
    },
    timeSeparator: {
      fontFamily: font,
      color: c.text,
      fontSize: fs(28),
      fontWeight: 'normal',
      marginTop: 2,
    },
    timeFormatPill: {
      alignSelf: 'center',
      borderRadius: 999,
      paddingHorizontal: 10,
      paddingVertical: 6 + tx,
      backgroundColor: '#FFF3D8',
    },
    timeFormatText: {
      fontFamily: font,
      color: c.yellow,
      fontSize: fs(12),
      fontWeight: 'normal',
    },
  });
}

export type AppStyles = ReturnType<typeof createAppStyles>;
