import {StyleSheet} from 'react-native';
import {ThemePalette} from '../constants/themePalettes';

export function createAppStyles(
  c: ThemePalette,
  fontScale: number,
  largeTouch: boolean,
  highVisibilityBorders: boolean,
) {
  const fs = (n: number) => Math.round(n * fontScale);
  const tx = largeTouch ? 5 : 0;
  const cardBorder = highVisibilityBorders ? 2 : 1;

  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: c.bg,
    },
    scrollContent: {
      paddingHorizontal: 16 + (largeTouch ? 2 : 0),
      paddingTop: 14 + tx,
      paddingBottom: 90 + tx,
    },
    rowBetween: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    appTitle: {
      fontSize: fs(28),
      fontWeight: '800',
      color: c.text,
    },
    headerRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 4,
    },
    settingsHeaderButton: {
      width: 48 + (largeTouch ? 6 : 0),
      height: 48 + (largeTouch ? 6 : 0),
      borderRadius: 12,
      backgroundColor: c.primary,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: highVisibilityBorders ? 2 : 0,
      borderColor: c.text,
    },
    settingsHeaderIcon: {
      color: '#FFFFFF',
      fontSize: fs(24),
      fontWeight: '700',
    },
    softText: {
      color: c.textSoft,
      fontSize: fs(15),
      marginTop: 4,
    },
    summaryCard: {
      backgroundColor: c.primaryDark,
      borderRadius: 16,
      padding: 14 + tx,
      marginBottom: 16,
      borderWidth: highVisibilityBorders ? 2 : 0,
      borderColor: c.line,
    },
    summaryLabel: {
      color: c.summaryMuted,
      fontSize: fs(13),
      fontWeight: '700',
    },
    summaryText: {
      marginTop: 8,
      color: '#FFFFFF',
      fontSize: fs(20),
      fontWeight: '700',
    },
    summaryPercent: {
      marginTop: 6,
      color: '#FFFFFF',
      fontSize: fs(14),
      fontWeight: '700',
      textAlign: 'right',
    },
    metricsRow: {
      flexDirection: 'row',
      gap: 8,
      marginBottom: 14,
    },
    metricCard: {
      flex: 1,
      borderRadius: 12,
      paddingVertical: 10 + tx,
      paddingHorizontal: 8,
      borderWidth: cardBorder,
    },
    metricCardTaken: {
      backgroundColor: c.metricTakenBg,
      borderColor: c.metricTakenBorder,
    },
    metricCardMissed: {
      backgroundColor: c.metricMissedBg,
      borderColor: c.metricMissedBorder,
    },
    metricCardPending: {
      backgroundColor: c.metricPendingBg,
      borderColor: c.metricPendingBorder,
    },
    metricTitle: {
      color: c.textSoft,
      fontSize: fs(13),
      fontWeight: '600',
    },
    metricValue: {
      marginTop: 4,
      color: c.text,
      fontSize: fs(24),
      fontWeight: '800',
    },
    progressBar: {
      marginTop: 10,
      height: 10 + (largeTouch ? 2 : 0),
      borderRadius: 8,
      backgroundColor: c.progressTrack,
      overflow: 'hidden',
    },
    progressFill: {
      height: '100%',
      backgroundColor: c.yellow,
    },
    sectionTitle: {
      color: c.text,
      fontSize: fs(22),
      fontWeight: '700',
      marginBottom: 12,
    },
    emptyCard: {
      backgroundColor: c.card,
      borderRadius: 14,
      padding: 16 + tx,
      borderWidth: cardBorder,
      borderColor: c.line,
      marginBottom: 12,
    },
    emptyTitle: {
      fontSize: fs(16),
      fontWeight: '700',
      color: c.text,
      marginBottom: 6,
    },
    medicineCard: {
      backgroundColor: c.card,
      borderRadius: 14,
      borderLeftWidth: 6,
      borderLeftColor: c.orange,
      padding: 14 + tx,
      marginBottom: 12,
      borderWidth: cardBorder,
      borderColor: c.line,
    },
    medicineName: {
      color: c.text,
      fontSize: fs(18),
      fontWeight: '700',
      marginBottom: 4,
    },
    actionRow: {
      marginTop: 12,
      flexDirection: 'row',
      gap: 8,
    },
    loggedTodayTag: {
      marginTop: 10,
      borderRadius: 10,
      paddingVertical: 7 + tx,
      paddingHorizontal: 10,
      backgroundColor: c.loggedTagBg,
    },
    loggedTodayTagText: {
      color: c.primaryDark,
      fontSize: fs(13),
      fontWeight: '700',
    },
    actionButton: {
      flex: 1,
      paddingVertical: 11 + tx,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: largeTouch ? 52 : 44,
    },
    actionButtonText: {
      color: '#FFF',
      fontWeight: '700',
      fontSize: fs(15),
    },
    actionPrimary: {
      backgroundColor: c.primary,
    },
    actionDanger: {
      backgroundColor: c.red,
    },
    bigButton: {
      marginTop: 8,
      backgroundColor: c.teal,
      borderRadius: 12,
      paddingVertical: 14 + tx,
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: largeTouch ? 56 : 48,
    },
    bigButtonText: {
      color: '#FFF',
      fontWeight: '800',
      fontSize: fs(15),
    },
    countBadge: {
      backgroundColor: c.frequencyActiveBg,
      borderRadius: 20,
      paddingHorizontal: 12,
      paddingVertical: 8 + tx,
    },
    countBadgeText: {
      color: c.primaryDark,
      fontSize: fs(13),
      fontWeight: '700',
    },
    historyDateNav: {
      marginTop: 16,
      marginBottom: 14,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: c.card,
      borderRadius: 12,
      padding: 10 + tx,
      borderWidth: cardBorder,
      borderColor: c.line,
    },
    navRoundButton: {
      width: 36 + (largeTouch ? 10 : 0),
      height: 36 + (largeTouch ? 10 : 0),
      borderRadius: 18 + (largeTouch ? 5 : 0),
      backgroundColor: c.navButtonBg,
      alignItems: 'center',
      justifyContent: 'center',
    },
    navRoundButtonText: {
      color: c.primaryDark,
      fontWeight: '700',
      fontSize: fs(18),
    },
    historyDateText: {
      color: c.text,
      fontWeight: '700',
      fontSize: fs(15),
      textTransform: 'capitalize',
    },
    historyCard: {
      backgroundColor: c.card,
      borderRadius: 12,
      borderWidth: cardBorder,
      borderColor: c.line,
      padding: 12 + tx,
      marginBottom: 10,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    statusPill: {
      paddingHorizontal: 12,
      paddingVertical: 6 + tx,
      borderRadius: 20,
    },
    statusPillText: {
      color: '#FFF',
      fontWeight: '700',
      fontSize: fs(12),
    },
    tipCard: {
      marginTop: 10,
      backgroundColor: c.card,
      borderRadius: 14,
      borderLeftWidth: 4,
      borderLeftColor: c.primary,
      borderWidth: cardBorder,
      borderColor: c.line,
      padding: 14 + tx,
    },
    tabBar: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      flexDirection: 'row',
      backgroundColor: c.tabBarBg,
      borderTopWidth: 1,
      borderTopColor: c.line,
    },
    tabButton: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 10 + tx,
      borderTopWidth: 3,
      borderTopColor: 'transparent',
      minHeight: largeTouch ? 58 : 50,
    },
    tabButtonActive: {
      borderTopColor: c.primary,
    },
    tabIcon: {
      fontSize: fs(20),
    },
    tabLabel: {
      marginTop: 2,
      fontSize: fs(12),
      color: c.textSoft,
      fontWeight: '600',
    },
    tabLabelActive: {
      color: c.primary,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.45)',
      justifyContent: 'flex-end',
    },
    modalCard: {
      backgroundColor: c.modalCardBg,
      borderTopLeftRadius: 16,
      borderTopRightRadius: 16,
      padding: 16 + tx,
    },
    modalTitle: {
      color: c.text,
      fontWeight: '800',
      fontSize: fs(20),
      marginBottom: 12,
    },
    inputLabel: {
      color: c.text,
      fontSize: fs(13),
      fontWeight: '700',
      marginBottom: 6,
    },
    input: {
      borderWidth: cardBorder,
      borderColor: c.line,
      borderRadius: 10,
      backgroundColor: c.inputBg,
      marginBottom: 10,
      paddingHorizontal: 12,
      paddingVertical: 10 + tx,
      color: c.text,
      fontSize: fs(16),
    },
    notesInput: {
      minHeight: 74,
      textAlignVertical: 'top',
    },
    frequencyWrap: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      marginBottom: 10,
    },
    frequencyItem: {
      borderWidth: cardBorder,
      borderColor: c.line,
      borderRadius: 20,
      paddingHorizontal: 12,
      paddingVertical: 8 + tx,
    },
    frequencyItemActive: {
      borderColor: c.primary,
      backgroundColor: c.frequencyActiveBg,
    },
    frequencyItemText: {
      color: c.textSoft,
      fontSize: fs(13),
      fontWeight: '600',
    },
    frequencyItemTextActive: {
      color: c.primaryDark,
    },
    cancelButton: {
      backgroundColor: c.cancelButtonBg,
    },
    cancelButtonText: {
      color: c.text,
      fontWeight: '700',
      fontSize: fs(14),
    },
    settingsSectionTitle: {
      color: c.primaryDark,
      fontSize: fs(13),
      fontWeight: '800',
      marginTop: 18,
      marginBottom: 8,
      letterSpacing: 0.5,
    },
    settingsRow: {
      backgroundColor: c.card,
      borderRadius: 12,
      padding: 14 + tx,
      marginBottom: 8,
      borderWidth: cardBorder,
      borderColor: c.line,
    },
    settingsRowLabel: {
      color: c.text,
      fontSize: fs(16),
      fontWeight: '700',
    },
    settingsRowHint: {
      color: c.textSoft,
      fontSize: fs(13),
      marginTop: 4,
    },
    settingsChipRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      marginTop: 10,
    },
    settingsChip: {
      borderWidth: cardBorder,
      borderColor: c.line,
      borderRadius: 20,
      paddingHorizontal: 14,
      paddingVertical: 10 + tx,
      backgroundColor: c.inputBg,
    },
    settingsChipActive: {
      borderColor: c.primary,
      backgroundColor: c.frequencyActiveBg,
    },
    settingsChipText: {
      color: c.textSoft,
      fontSize: fs(14),
      fontWeight: '600',
    },
    settingsChipTextActive: {
      color: c.primaryDark,
      fontWeight: '700',
    },
    settingsToggleRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginTop: 10,
    },
    settingsCloseBar: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 8,
    },
    settingsCloseText: {
      color: c.primary,
      fontSize: fs(16),
      fontWeight: '700',
    },
    settingsTitleMain: {
      color: c.text,
      fontSize: fs(22),
      fontWeight: '800',
    },
  });
}

export type AppStyles = ReturnType<typeof createAppStyles>;
